game.Henk = [
	"WELKOM IN DE LAWEI.",
	"WE HEBBEN EEN PROBLEEM DAT ALLEEN \nJIJ KAN OPLOSSEN.",
	"WIL JE ONS DAARBIJ HELPEN?",
	"JE MOET NAAR DIE PLEK EN DAN MOET \nJE DAT DOEN.",
	"DAARNA GA JE NAAR DE ANDERE PLEK EN \nDOE JE DIT.",
	"ALS JE DAARMEE KLAAR BENT KAN JE \nDOOR MET HET ZOEKEN VAN DAT DING.",
	"ALS JE DAT DING HEBT GEVONDEN LEVER \nJE HET BIJ DIE PERSOON IN.",
	"DIE PERSOON VERTELT JE WAAR JE DAN \nHEEN MOET.",
]

game.Kees = [
	"WAAR BEN JE ME BEZIG?",
	"DAT MOET JE NIET ZO DOEN.",
	"JE MOET NAAR HET PODIUM OM DAT DING TE VINDEN.",
	"MAAR OM DAAR TE KOMEN MOET JE WEL DAT ANDERE DING BIJ JE HEBBEN.",
	"ALS JE DAT ANDERE DING NIET BIJ JE HEBT WORD JE ERUIT GEZET.",
]