game.dialog = [
	"DEZE MELOEN IS VEEL BETER DAN UNITY",
	"HOUD JE BEK JONGUH, MET JE KUT KOP",
	"IK HEB TENMINSTE EEN KOP! MOSLIM!",
	"LEKKER IN VEROTTE BANANEN KNIJPEN",
	"WEET JE WAT BANANEN EIGNELIJKE BETEKEN?",
	"NEE",
	"BAVIANEN... VOER..",
	"JIJ BENT BAVIANENVOER!",
	"LIJK IK OP EEN BANAAN?",
	"JA!",
	"IK DACHT HET VAN NIET, MENEER",
	"IK WERK TENMINSTE NIET IN CONSTRUCT"
]